### ISSUE TITLE
Plugins: Command FallBack

### ISSUE THREAD

**Issue by ementalo** [chraft/c-raft#110]
If plugins have commands that conflict do the following:

Try to default to shortcuts / aliases.
If these conflict
The conflicting command is registered as PluginName.Command

RealWorld Scenario:

Plugin A has /give and Plugin B has /give

Plugin A loads first so Plugin B needs to look at alternatives.
Check Plugin B's shortcuts to see if any exist
If not  use Plugin B's shortcut as the command
Otherwise use PluginB.CommandName

**Comment by taugit** [comment]
Collision check has been implemented in [this commit](https://github.com/chraft/c-raft/commit/1f3cda1a4a49793c21e25a7f5ae37f8e028d5592).
If two or more commands have the same name or shortcut it'll be proposed to clearly indicate the command by calling it like /PluginName:CommandName (case insensitive).
