### ISSUE TITLE
Net - Chunk compression: Replace lkvm Deflate

### ISSUE THREAD

**Issue by justinstenning** [chraft/c-raft#114]
The Chunk compression should use a native C# deflate.

See: http://dotnetzip.codeplex.com/

Supports parallel compression, swap in replacements for DeflateStream and GZipStream.

Faster than framework version.

**Comment by ementalo** [comment]
boo yah, yeah I meant to add this as an issue

**Comment by justinstenning** [comment]
DotNetZip has a bug in the ZlibStream for Deflate - used ICSharpZipLib instead (1346c6a8917815ca2a15796fd21f4578c32b7515).
