### ISSUE TITLE
Blocks: Implement a fallback default BlockClass for unknown block types

### ISSUE THREAD

**Issue by justinstenning** [chraft/c-raft#125]
It is possible in the Drowning/Suffocation check that the block type is invalid (from memory i think 255).

I have seen this once, and it has been reported on IRC by another a couple times.

To get around this rare state, a default block class could be implemented that is returned for any unknown block type. This will prevent the null reference checks.

The block class should return false for the various IsLiquid checks etc... and perform no actions.

**Comment by justinstenning** [comment]
Example of the problem occuring: http://prntscr.com/3oxdp

**Comment by DecoyLex** [comment]
I'm testing a possible fix.

BlockHelper.Instance seems to return null if the block is not found.  Fix: return air

**Comment by taugit** [comment]
We can add an appropriate block class, like BlockInvalid or perform a check on a GetBlockId() result before calling the BlockHelper. Actually I like the second way more.

**Comment by justinstenning** [comment]
I have wrapped the specific place that had this exception with a check that prevents the null reference exception. So probably not such a high priority now - unless the error occurs elsewhere - not pushed yet.

**Comment by taugit** [comment]
Now the World.GetBlockId() method return a nullable byte. You have to check whether the value is null before calling BlockHelper.Instance(). Does this fix closes the issue? Or how can i reproduce it? The only way to get a null block instance - is to pass a non-existent block id which has been fixed as described above.
