### ISSUE TITLE
Wrong server hash dimension

### ISSUE THREAD

**Issue by Smjert** [chraft/c-raft#136]
Notch uses a 16 characters long string as the server hash to send by handshake packet, we use an MD5 that's 32 chars, that's why the test client complains about the field being too small. 
I think we should adhere to the standard so doing just as Notch does, generate a random long value and transform it into a hexstring unless there's a particular reason to make it unique.

**Comment by ementalo** [comment]
I think we should do it the notch way when it comes to auth
