### ISSUE TITLE
1.3.1 Client. Cannot login. "Connection Lost", "End of stream"

### ISSUE THREAD

**Issue by keneo** [chraft/c-raft#168]
I just begun to play with C-raft server (version as of Jun 03, 2012). 

I haven't succedded to login into my server lunched from VS.

I'm using the current vanilla minecraft gui client. (Version: 1.3.1.)

Whenever I try to login, the client hungs up a few seconds ("Logging in...") and then sais:
"Connection Lost"
"End of stream"

From my noob perspective it seems like the server waits for client gui to authenticate, but the client is still waiting for something else.
# Chronologically:
1. I click "Join Server"
   - Client:  "Logging in..."
   - Server: 12:27:18 [INFO] Clients online: 1
   - Server: 12:27:18 [INFO] Starting client
2. (for 6 seconds nothing happens)
3. appearently disconnected
   - Client "Connection Lost" , "End of stream"
   - Server 12:27:34 [INFO] Disposing
   - Server 12:27:34 [INFO] Clients online: 0
# I've made some debugging

I managed to do some debugging and found that:
- authentication never happened yet (Server.UseOfficalAuthentication was never read)
- actual client disconnecting is triggered in Client.CheckAlive()
- unhandled exception is thrown in a server thread in PacketHandlers.ReadHandshake() -> hp.Read(reader) -> stream.ReadString16(64): "String field too long"
  - The background task ProcessReadQueue started with Task.Factory.StartNew throws unhandled exception without a log message.
  - I think some more exception handling is nessesary in ProcessReadQueue()

**Comment by Smjert** [comment]
Thank you for your detailed report, you have this issue because C#raft doesn't support 1.3.1 protocol currently. The update is in progress though. If you have other problems or just want to talk, join us on irc EsperNet, #c#raft.

**Comment by keneo** [comment]
@Smejrt: Could you please tell which client versions are fine to use with this version of C-raft?

It could be a good idea to maintain such information on the readme file.
