### ISSUE TITLE
Crash on user login

### ISSUE THREAD

**Issue by FormallyMyles** [chraft/c-raft#172]
Build: v0.0.0.605
Description Of Issue: Server becomes not responding and crashes.

Screen Shot of Console: http://my.nf/xUEgNn.png
More Errors: http://my.nf/RfRfsa.png
Pastebin of server.log: http://pastebin.com/LV8K1KaL

To Replicate:
1. Start Server
2. Login to Server
3. Wait then it crashes. (About 10 seconds)
This may be to do with mob scheduling.

System:
Win 7 64 Bit
8GB Ram
2.1Ghz x 2

**Comment by ementalo** [comment]
Cannot reproduce anymore
