### ISSUE TITLE
Crafting - QTY issue?

### ISSUE THREAD

**Issue by ementalo** [chraft/c-raft#24]
Make workbench
2 wood in a line to attempt to craft stick
the sticks with a QTY of 4 flash briefly leaving you with a sole lonely stick

**Comment by justinstenning** [comment]
Was because of incorrect recipes in Recipe.dat - need to check the rest of the recipes still.

**Comment by ementalo** [comment]
I think there is probably better way to do recipies then the format of that dat file, maybe like csv format but eh that can be for another time
