### ISSUE TITLE
Fix EntityBase.TeleportTo()

### ISSUE THREAD

**Issue by DecoyLex** [chraft/c-raft#29]
When using /spawn you are sent to .0 of the spawn on the Y axis.  This has happened every time I've used /spawn after "fixing" it.

Steps to recreate:
1. Login
2. Use /spawn

No exception.

Video: http://www.youtube.com/watch?v=fbFLE7smSAo

**Comment by ementalo** [comment]
I haven't dug deep but maybe its because the World.Spawn.X / Y / Z's are ints? they are defined from the Settings / app.config

**Comment by justinstenning** [comment]
Its something funkier than that, respawn on death is fine, it is as if the client has the person stuck inside the block they are standing on, very strange.
