### ISSUE TITLE
Fall damage

### ISSUE THREAD

**Issue by ementalo** [chraft/c-raft#31]
http://mc.kev009.com/Protocol#Player_.280x0A.29

When dropping from sufficient height, fall damage is applied when this state goes from False to True. The amount of damage applied is based on the point where it last changed from True to False. Note that there are several movement related packets containing this state.

**Comment by justinstenning** [comment]
Fall damage calculation is now made - but call to damage method is not in place.

The Client.DamageClient requires some work, currently it assumes damage from an EntityBase, whereas we need to support a whole range of damage sources:
1. Client Item Damage (damage from clients with swords, arrows, TNT, and so on)
2. Mob Damage (various mobs)
3. Natural Damage
   - Fall Damage
   - Drowning
   - Suffocation
   - Cacti
   - Lava

See #36
