### ISSUE TITLE
Require a more generic Client.DamageClient

### ISSUE THREAD

**Issue by justinstenning** [chraft/c-raft#36]
A DamageClient function is required that better supports the different damage types so that the damage can be applied in one place, with a variety of parameters determining the amount of damage:

Currently it assumes damage from an EntityBase, whereas we need to support a whole range of damage sources:
1. Client Item Damage (damage from clients with swords, arrows, TNT, and so on)
2. Mob Damage (various mobs)
3. Natural Damage
   - Fall Damage
   - Drowning
   - Suffocation
   - Cacti
   - Lava

required for #30, #31, #32

**Comment by ementalo** [comment]
basic implimentation in d581a8461c6aa504a88f. Will need some extending and PluginEvents will need extending to take a damage cause. It is more a starting point to get us going

**Comment by justinstenning** [comment]
I agree - events should be raised from the DamageClient method, not in each location.
