### ISSUE TITLE
Persistent containers need to use a single itemstack list per container

### ISSUE THREAD

**Issue by justinstenning** [chraft/c-raft#38]
Persistent containers can be opened by more than one client and in the case of a furnace or dispenser, by the world itself.

Therefore multiple clients need to be able to subscribe to the same itemstack list events based on changes from different clients and world processes (such as dispenser or furnace).

Necessary to complete #3

**Comment by justinstenning** [comment]
Taking a break from chests/furnaces for a bit - unassigning myself until I get back to it (or someone else does it)

**Comment by taugit** [comment]
One more improvement required: right now the instances of the containers are kept in memory only while they have at least one interface (one player is looking into them).
Pros: less memory usage - lots of containers in a world could result in a permanent memory usage. Actually even 1000 containers in a world - which is a high amount - wouldn't eat too much memory.
Cons: container's content is being loaded too often, could be an issue for things like dispensers (trigger fire -> create instance -> load content -> fire an item (if any) -> save content -> destroy instance), also it's harder to manage the containers.

What will be done:
1. Persistent containers (instances) will be kept in memory
2. They will be created/destroyed upon chunk loading/unloading. We'll just attach the player's interface to it to begin working with it and receive an updates.

Also few non-critical improvements are planned.
