### ISSUE TITLE
Mob AI - movement

### ISSUE THREAD

**Issue by ementalo** [chraft/c-raft#4]
Working mob ai, currently mobs act like they are at a rave

**Comment by justinstenning** [comment]
(work continues on this - a lot of reworking in EntityBase is taking place)

**Comment by justinstenning** [comment]
8bf69dd6fe3545da2a9f08e042659ba4837e9616
9c6a9bf76d8c3bdf0b09cfd5f3e1c99ce0eb124d
af44fc76a5d7052ea18625d10da5de32ba0a65f0
556f21f224316b0fa21851a3ceaed4e1e93d8b8e

The above commits implement basic movement support for Mobs - THERE ARE STILL ISSUES.

Some of the maths needs more work, it moves too fast along one of the axes.

**Comment by justinstenning** [comment]
Closing as the basics for movement, following and path finding are now in place - more specific AI is still required
