### ISSUE TITLE
Block data not working correctly in MapChunkPacket for Furnace

### ISSUE THREAD

**Issue by justinstenning** [chraft/c-raft#43]
To reproduce:

1) Place furnace (http://i.imgur.com/2FomB.png)
2) Exit
3) Enter
4) Furnace has no direction - all faces have the same blank image (http://i.imgur.com/f4MDg.png)

Testing of other blocks has not been done.

Upon testing of the MapChunkPacket it appears that everything is working as it should be - but clearly something isn't quite right (reference: http://mc.kev009.com/Protocol#Map_Chunk_.280x33.29).

**Comment by Smjert** [comment]
This could be because how you send MapChunkPacket is incorrect (the writing of the data into the array and not only). I have solved this in my branch, develop, using NibbleArray and CopyTo that is also much more clear.

**Comment by ementalo** [comment]
This is resolved
