### ISSUE TITLE
Plugin API should be a separate dll 

### ISSUE THREAD

**Issue by ementalo** [chraft/c-raft#47]

**Comment by ementalo** [comment]
Plugin api should really be a seperate project referenced by the main server

**Comment by DecoyLex** [comment]
I do see and agree with your point, however I will not have the time to do this for at most a few months as I am currently moving into a new house.  So, if anyone is feeling courageous and would like to write it before then I would greatly appreciate it.

**Comment by ementalo** [comment]
I will give it ago, thanks for your contribution so far, hope the move isn't too stressful and will catch you on the other side hopefully :D

**Comment by ementalo** [comment]
Un-assigned myself, will maybe pick up at some point

**Comment by ementalo** [comment]
This is done now Chraft.PluginSystem.dll to be documented
